zuul:
  prefix: /api
  routes:
    catalog: 
      path: /catalog/**
      serviceId: catalog-client
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765
management:
  security:
    enabled: false